#!/bin/bash
# Setup configuration directories
export XDG_CONFIG_HOME="$HOME/.config"
mkdir -p "$XDG_CONFIG_HOME"
mkdir -p "$XDG_CONFIG_HOME/nixpkgs"

# Link your Nix configuration file
ln -sf "$PWD/.bash_profile" "$HOME"/.bash_profile
ln -sf "$PWD/.bashrc" "$HOME"/.bashrc
ln -sf "$PWD/.inputrc" "$HOME"/.inputrc
ln -sf "$PWD/config.nix" "$XDG_CONFIG_HOME/nixpkgs/config.nix"
ln -sf "$PWD/nvim" "$XDG_CONFIG_HOME"/nvim
#ln -sf "$PWD/.zshrc" "/home/vscode/.zshrc"
ln -sf "$PWD/starship.toml" "$HOME/.config/starship.toml"

# Install Nix packages from config.nix
nix-env -iA nixpkgs.myPackages
